### ISSUE TITLE
Morning Session Suggestions:

### ISSUE THREAD

**Issue by orozCoding** [AdornChoga/Awesome-Books-ES6#5]
Great job with the project so far! ❤️ 

Here are some suggestions that we think could improve it:
- In your index.js we'd suggest you to makit a little bit more DRY by creating a function (and a loop) to add the event listener that applies the mouseChange function.
- In the function addBook at your edit-library module, you could call your already created fetchData function, so you make it DRY.
- The function and the Class contained in the username.js module could be splited in different files.

Keep it going ! 💪

**Comment by AdornChoga** [comment]
Thank you everybody for the suggested improvements. I will go ahead and fix these issues. Thanks a lot.
